version: '2.1'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    container_name: clanetest
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8000:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=crane"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD="
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_ROOT_PASSWORD="
    ports:
        - "33061:3306"

volumes:
  dbdata: